//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoH_Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodeErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoH_Resources.Resources.CodeErrors", typeof(CodeErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can`t add this unit to this hex..
        /// </summary>
        public static string CantAddUnitToHex {
            get {
                return ResourceManager.GetString("CantAddUnitToHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can`t create team with no players.
        /// </summary>
        public static string CantCreateEmptyTeam {
            get {
                return ResourceManager.GetString("CantCreateEmptyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can`t find type by name.
        /// </summary>
        public static string CantFindType {
            get {
                return ResourceManager.GetString("CantFindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File doesn`t exists..
        /// </summary>
        public static string FileDoesntExists {
            get {
                return ResourceManager.GetString("FileDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can`t create Hex.
        /// </summary>
        public static string InvalidHexCreation {
            get {
                return ResourceManager.GetString("InvalidHexCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can`t create Hex by reflection, Hex must be inherited from BaseHex.
        /// </summary>
        public static string InvalidHexType {
            get {
                return ResourceManager.GetString("InvalidHexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map isn`t valid, center hex is null.
        /// </summary>
        public static string MapNotCreated {
            get {
                return ResourceManager.GetString("MapNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no suitable map size in defaults.
        /// </summary>
        public static string NoSuitableMapSize {
            get {
                return ResourceManager.GetString("NoSuitableMapSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type isn`t inherited from GameObject type.
        /// </summary>
        public static string TypeIsntGameObject {
            get {
                return ResourceManager.GetString("TypeIsntGameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  type have no proper constructor.
        /// </summary>
        public static string TypeNoConstructor {
            get {
                return ResourceManager.GetString("TypeNoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit isnt registered on UnitManager.
        /// </summary>
        public static string UnitIsntInUm {
            get {
                return ResourceManager.GetString("UnitIsntInUm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit isn`t on this hex.
        /// </summary>
        public static string UnitIsntOnHex {
            get {
                return ResourceManager.GetString("UnitIsntOnHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown UnitTypeAttribute.
        /// </summary>
        public static string UnitTypeAttributeNotExist {
            get {
                return ResourceManager.GetString("UnitTypeAttributeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown HexDirection.
        /// </summary>
        public static string UnknownHexDirection {
            get {
                return ResourceManager.GetString("UnknownHexDirection", resourceCulture);
            }
        }
    }
}
