//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoH_Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MapJsonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapJsonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoH_Resources.Resources.MapJsonStrings", typeof(MapJsonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BottomHexId.
        /// </summary>
        public static string BottomHexId {
            get {
                return ResourceManager.GetString("BottomHexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BottomLeftHexId.
        /// </summary>
        public static string BottomLeftHexId {
            get {
                return ResourceManager.GetString("BottomLeftHexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BottomRightHexId.
        /// </summary>
        public static string BottomRightHexId {
            get {
                return ResourceManager.GetString("BottomRightHexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexes.
        /// </summary>
        public static string Hexes {
            get {
                return ResourceManager.GetString("Hexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string HexId {
            get {
                return ResourceManager.GetString("HexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LengthX.
        /// </summary>
        public static string LengthX {
            get {
                return ResourceManager.GetString("LengthX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LengthY.
        /// </summary>
        public static string LengthY {
            get {
                return ResourceManager.GetString("LengthY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetX.
        /// </summary>
        public static string OffsetX {
            get {
                return ResourceManager.GetString("OffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetY.
        /// </summary>
        public static string OffsetY {
            get {
                return ResourceManager.GetString("OffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopHexId.
        /// </summary>
        public static string TopHexId {
            get {
                return ResourceManager.GetString("TopHexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopLeftHexId.
        /// </summary>
        public static string TopLeftHexId {
            get {
                return ResourceManager.GetString("TopLeftHexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopRightHexId.
        /// </summary>
        public static string TopRightHexId {
            get {
                return ResourceManager.GetString("TopRightHexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitsId.
        /// </summary>
        public static string UnitsId {
            get {
                return ResourceManager.GetString("UnitsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string XCoord {
            get {
                return ResourceManager.GetString("XCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string YCoord {
            get {
                return ResourceManager.GetString("YCoord", resourceCulture);
            }
        }
    }
}
