//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoH_classes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapJsonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapJsonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoH_classes.Resources.MapJsonStrings", typeof(MapJsonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexes.
        /// </summary>
        internal static string Hexes {
            get {
                return ResourceManager.GetString("Hexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string HexId {
            get {
                return ResourceManager.GetString("HexId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LenghtX.
        /// </summary>
        internal static string LenghtX {
            get {
                return ResourceManager.GetString("LenghtX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LenghtY.
        /// </summary>
        internal static string LenghtY {
            get {
                return ResourceManager.GetString("LenghtY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetX.
        /// </summary>
        internal static string OffsetX {
            get {
                return ResourceManager.GetString("OffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetY.
        /// </summary>
        internal static string OffsetY {
            get {
                return ResourceManager.GetString("OffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string XCoord {
            get {
                return ResourceManager.GetString("XCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YCoord {
            get {
                return ResourceManager.GetString("YCoord", resourceCulture);
            }
        }
    }
}
